//! `SeaORM` Entity. Generated by sea-orm-codegen 0.10.6

use sea_orm::entity::prelude::*;
use serde_json::Value;
#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "router")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: u32,
    #[sea_orm(unique)]
    pub path: String,
    pub proxy_type: String,
    pub belong: Option<String>,
    pub status: Option<i8>,
    #[sea_orm(column_type = "Text", nullable)]
    pub config: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub response: Option<Value>,
    pub extension: String,
    pub description: String,
    pub create_time: DateTime,
    pub modify_time: DateTime,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
