config = [
    [
        {api="test/database_tables", params={abc="simple1"}, name="abc1", recovery=false},
        {api="test/database_tables", params={abc="simple2"}, name="abc2", recovery=false}
    ]
]